###########
# site.url, site.title

title: "Gymrek Lab"

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: ""
url:  "http://gymreklab.github.io"
description: "Gymrek Lab website UCSD"

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

# per the advice here: https://stackoverflow.com/questions/29519469/hide-an-entry-from-the-toc-table-of-contents-in-jekyll/29521660#29521660
# from http://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      hide: false
